services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092 # External access (if needed)
      - 29092:29092 # Internal Docker network access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka-producer-demo:
    build:
      context: ./KafkaProducerDemo
      dockerfile: Dockerfile
    depends_on:
      - kafka
    ports:
      - 5000:5000 # Map host port 5000 to container port 5000
    environment:
      ASPNETCORE_URLS: "http://+:5000"
      # Point to Kafka using the internal network alias
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - kafka-net

  kafka-consumer-demo:
    build:
      context: ./KafkaConsumerDemo
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - mongo
    ports:
      - 5001:5001 # Map host port 5001 to container port 5001
    environment:
      ASPNETCORE_URLS: "http://+:5001"
      # Point to Kafka using the internal network alias
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - kafka-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - kafka-net

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    depends_on:
      - kafka
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge

volumes:
  zookeeper-data:
  zookeeper-log:
  kafka-data:
  mongo-data:
